<?php
namespace RHEditorBlockStarter;

class Plugin
{
    /**
     * Static class initializer that hooks into WordPress
     */
    public static function init()
    {
        $self = new self();

        add_action('plugins_loaded', [$self, 'loadTextDomain']);
        add_action('wp_loaded', [$self, 'initBlock']);
    }

    /**
     * Load the plugin text domain
     */
    public function loadTextDomain()
    {
        load_plugin_textdomain(
            'rh-editor-block-starter',
            false,
            dirname(plugin_basename(__DIR__)) . '/languages'
        );
    }

    /**
     * Block initializer
     *
     * Handles registering scripts, styles and block types and sets up scripts translations.
     */
    public function initBlock()
    {
        // Load the asset file generated by `@wordpress/scripts`
        $assetFilePath = plugin_dir_path(__DIR__) . 'build/index.asset.php';

        // Bail if there is no asset file
        if (!file_exists($assetFilePath)) {
            return false;
        }

        $assetFile = include($assetFilePath);

        wp_register_script(
            'rh-editor-block-starter-editor-js',
            plugins_url('build/index.js', __DIR__),
            $assetFile['dependencies'],
            $assetFile['version']
        );

        wp_register_style(
            'rh-editor-block-starter-editor-css',
            plugins_url('assets/styles/editor.css', __DIR__),
            ['wp-edit-blocks'],
            filemtime(plugin_dir_path(__DIR__) . 'assets/styles/editor.css')
        );

        wp_register_style(
            'rh-editor-block-starter-css',
            plugins_url('assets/styles/style.css', __DIR__),
            [],
            filemtime(plugin_dir_path(__DIR__) . 'assets/styles/style.css')
        );

        // Delete this if you have a server-side rendered block. It is registered in the Render class.
        register_block_type('werbelinie/rh-editor-block-starter', [
            'editor_script' => 'rh-editor-block-starter-editor-js',
            'editor_style' => 'rh-editor-block-starter-editor-css',
            'style' => 'rh-editor-block-starter-css',
        ]);

        wp_set_script_translations(
            'rh-editor-block-starter-editor-js',
            'rh-editor-block-starter',
            plugin_dir_path(__FILE__) . 'languages'
        );
    }
}

/** Initialize a custom post type */
// CustomPostType::init();
/** Uncomment if you use server-side render */
// EditorBlock\Render::init();
